// Code generated by "stringer -type=HashType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashTypeUnknown-0]
	_ = x[HashTypeBcrypt-1]
	_ = x[HashTypeSHA1-2]
}

const _HashType_name = "HashTypeUnknownHashTypeBcryptHashTypeSHA1"

var _HashType_index = [...]uint8{0, 15, 29, 41}

func (i HashType) String() string {
	if i < 0 || i >= HashType(len(_HashType_index)-1) {
		return "HashType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashType_name[_HashType_index[i]:_HashType_index[i+1]]
}
