apiVersion: v1
kind: Service
metadata:
  name: hydrui
  labels:
    app: hydrui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hydrui
