export enum ContentUpdateAction {
  ADD = 0,
  DELETE = 1,
  PEND = 2,
  RESCIND_PEND = 3,
  PETITION = 4,
  RESCIND_PETITION = 5,
  EDIT_LOG = 6,
  ARCHIVE = 7,
  INBOX = 8,
  RATING = 9,
  DENY_PEND = 11,
  DENY_PETITION = 12,
  ADVANCED = 13,
  UNDELETE = 14,
  SET = 15,
  FLIP = 16,
  CLEAR_DELETE_RECORD = 17,
  INCREMENT = 18,
  DECREMENT = 19,
  MOVE = 20,
  DELETE_FROM_SOURCE_AFTER_MIGRATE = 21,
}

export const CONTENT_UPDATE_STRINGS: Record<ContentUpdateAction, string> = {
  [ContentUpdateAction.ADD]: "add",
  [ContentUpdateAction.DELETE]: "delete",
  [ContentUpdateAction.PEND]: "pending",
  [ContentUpdateAction.RESCIND_PEND]: "rescind pending",
  [ContentUpdateAction.PETITION]: "petition",
  [ContentUpdateAction.RESCIND_PETITION]: "rescind petition",
  [ContentUpdateAction.EDIT_LOG]: "edit log",
  [ContentUpdateAction.ARCHIVE]: "archive",
  [ContentUpdateAction.INBOX]: "inbox",
  [ContentUpdateAction.RATING]: "rating",
  [ContentUpdateAction.DENY_PEND]: "deny pend",
  [ContentUpdateAction.DENY_PETITION]: "deny petition",
  [ContentUpdateAction.ADVANCED]: "advanced",
  [ContentUpdateAction.UNDELETE]: "undelete",
  [ContentUpdateAction.SET]: "set",
  [ContentUpdateAction.FLIP]: "flip on/off",
  [ContentUpdateAction.CLEAR_DELETE_RECORD]: "clear deletion record",
  [ContentUpdateAction.INCREMENT]: "increment",
  [ContentUpdateAction.DECREMENT]: "decrement",
  [ContentUpdateAction.MOVE]: "move",
  [ContentUpdateAction.DELETE_FROM_SOURCE_AFTER_MIGRATE]:
    "delete from source after migrate",
};
