// Based on https://github.com/floogulinc/hydrus-web/blob/dev/src/app/hydrus-file-mimes.ts
// and https://github.com/hydrusnetwork/hydrus/blob/master/hydrus/core/HydrusConstants.py

export enum HydrusFileType {
  APPLICATION_HYDRUS_CLIENT_COLLECTION = 0,
  IMAGE_JPEG = 1,
  IMAGE_PNG = 2,
  ANIMATION_GIF = 3,
  IMAGE_BMP = 4,
  APPLICATION_FLASH = 5,
  APPLICATION_YAML = 6,
  IMAGE_ICON = 7,
  TEXT_HTML = 8,
  VIDEO_FLV = 9,
  APPLICATION_PDF = 10,
  APPLICATION_ZIP = 11,
  APPLICATION_HYDRUS_ENCRYPTED_ZIP = 12,
  AUDIO_MP3 = 13,
  VIDEO_MP4 = 14,
  AUDIO_OGG = 15,
  AUDIO_FLAC = 16,
  AUDIO_WMA = 17,
  VIDEO_WMV = 18,
  UNDETERMINED_WM = 19,
  VIDEO_MKV = 20,
  VIDEO_WEBM = 21,
  APPLICATION_JSON = 22,
  ANIMATION_APNG = 23,
  UNDETERMINED_PNG = 24,
  VIDEO_MPEG = 25,
  VIDEO_MOV = 26,
  VIDEO_AVI = 27,
  APPLICATION_HYDRUS_UPDATE_DEFINITIONS = 28,
  APPLICATION_HYDRUS_UPDATE_CONTENT = 29,
  TEXT_PLAIN = 30,
  APPLICATION_RAR = 31,
  APPLICATION_7Z = 32,
  IMAGE_WEBP = 33,
  IMAGE_TIFF = 34,
  APPLICATION_PSD = 35,
  AUDIO_M4A = 36,
  VIDEO_REALMEDIA = 37,
  AUDIO_REALMEDIA = 38,
  AUDIO_TRUEAUDIO = 39,
  GENERAL_AUDIO = 40,
  GENERAL_IMAGE = 41,
  GENERAL_VIDEO = 42,
  GENERAL_APPLICATION = 43,
  GENERAL_ANIMATION = 44,
  APPLICATION_CLIP = 45,
  AUDIO_WAVE = 46,
  VIDEO_OGV = 47,
  AUDIO_MKV = 48,
  AUDIO_MP4 = 49,
  UNDETERMINED_MP4 = 50,
  APPLICATION_CBOR = 51,
  APPLICATION_WINDOWS_EXE = 52,
  AUDIO_WAVPACK = 53,
  APPLICATION_SAI2 = 54,
  APPLICATION_KRITA = 55,
  IMAGE_SVG = 56,
  APPLICATION_XCF = 57,
  APPLICATION_GZIP = 58,
  GENERAL_APPLICATION_ARCHIVE = 59,
  GENERAL_IMAGE_PROJECT = 60,
  IMAGE_HEIF = 61,
  IMAGE_HEIF_SEQUENCE = 62,
  IMAGE_HEIC = 63,
  IMAGE_HEIC_SEQUENCE = 64,
  IMAGE_AVIF = 65,
  IMAGE_AVIF_SEQUENCE = 66,
  UNDETERMINED_GIF = 67,
  IMAGE_GIF = 68,
  APPLICATION_PROCREATE = 69,
  IMAGE_QOI = 70,
  APPLICATION_EPUB = 71,
  APPLICATION_DJVU = 72,
  APPLICATION_CBZ = 73,
  ANIMATION_UGOIRA = 74,
  APPLICATION_RTF = 75,
  APPLICATION_MICROSOFT_OPEN_XML_DOCX = 76,
  APPLICATION_MICROSOFT_OPEN_XML_XLSX = 77,
  APPLICATION_MICROSOFT_OPEN_XML_PPTX = 78,
  UNDETERMINED_OLE = 79,
  APPLICATION_DOC = 80,
  APPLICATION_XLS = 81,
  APPLICATION_PPT = 82,
  ANIMATION_WEBP = 83,
  UNDETERMINED_WEBP = 84,
  IMAGE_JXL = 85,
  APPLICATION_OCTET_STREAM = 100,
  APPLICATION_UNKNOWN = 101,
}

const IMAGES = [
  HydrusFileType.IMAGE_JPEG,
  HydrusFileType.IMAGE_PNG,
  HydrusFileType.IMAGE_GIF,
  HydrusFileType.IMAGE_WEBP,
  HydrusFileType.IMAGE_AVIF,
  HydrusFileType.IMAGE_JXL,
  HydrusFileType.IMAGE_BMP,
  HydrusFileType.IMAGE_HEIC,
  HydrusFileType.IMAGE_HEIF,
  HydrusFileType.IMAGE_ICON,
  HydrusFileType.IMAGE_QOI,
  HydrusFileType.IMAGE_TIFF,
];

const ANIMATIONS = [
  HydrusFileType.ANIMATION_GIF,
  HydrusFileType.ANIMATION_APNG,
  HydrusFileType.ANIMATION_WEBP,
  HydrusFileType.IMAGE_HEIF_SEQUENCE,
  HydrusFileType.IMAGE_HEIC_SEQUENCE,
  HydrusFileType.IMAGE_AVIF_SEQUENCE,
  HydrusFileType.ANIMATION_UGOIRA,
];

const AUDIO = [
  HydrusFileType.AUDIO_MP3,
  HydrusFileType.AUDIO_OGG,
  HydrusFileType.AUDIO_FLAC,
  HydrusFileType.AUDIO_M4A,
  HydrusFileType.AUDIO_MKV,
  HydrusFileType.AUDIO_MP4,
  HydrusFileType.AUDIO_REALMEDIA,
  HydrusFileType.AUDIO_TRUEAUDIO,
  HydrusFileType.AUDIO_WAVE,
  HydrusFileType.AUDIO_WAVPACK,
  HydrusFileType.AUDIO_WMA,
];

const VIDEO = [
  HydrusFileType.VIDEO_MP4,
  HydrusFileType.VIDEO_WEBM,
  HydrusFileType.VIDEO_MKV,
  HydrusFileType.VIDEO_AVI,
  HydrusFileType.VIDEO_FLV,
  HydrusFileType.VIDEO_MOV,
  HydrusFileType.VIDEO_MPEG,
  HydrusFileType.VIDEO_OGV,
  HydrusFileType.VIDEO_REALMEDIA,
  HydrusFileType.VIDEO_WMV,
];

const APPLICATIONS = [
  HydrusFileType.APPLICATION_FLASH,
  HydrusFileType.APPLICATION_PDF,
  HydrusFileType.APPLICATION_EPUB,
  HydrusFileType.APPLICATION_DJVU,
  HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_DOCX,
  HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_XLSX,
  HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_PPTX,
  HydrusFileType.APPLICATION_DOC,
  HydrusFileType.APPLICATION_XLS,
  HydrusFileType.APPLICATION_PPT,
  HydrusFileType.APPLICATION_RTF,
];

const IMAGE_PROJECT_FILES = [
  HydrusFileType.APPLICATION_PSD,
  HydrusFileType.APPLICATION_CLIP,
  HydrusFileType.APPLICATION_SAI2,
  HydrusFileType.APPLICATION_KRITA,
  HydrusFileType.IMAGE_SVG,
  HydrusFileType.APPLICATION_XCF,
  HydrusFileType.APPLICATION_PROCREATE,
];

const ARCHIVES = [
  HydrusFileType.APPLICATION_CBZ,
  HydrusFileType.APPLICATION_7Z,
  HydrusFileType.APPLICATION_GZIP,
  HydrusFileType.APPLICATION_RAR,
  HydrusFileType.APPLICATION_ZIP,
];

export const filetypeEnumToString: Map<HydrusFileType, string> = new Map([
  [HydrusFileType.APPLICATION_HYDRUS_CLIENT_COLLECTION, "collection"],
  [HydrusFileType.IMAGE_JPEG, "jpeg"],
  [HydrusFileType.IMAGE_PNG, "png"],
  [HydrusFileType.ANIMATION_APNG, "apng"],
  [HydrusFileType.IMAGE_GIF, "static gif"],
  [HydrusFileType.ANIMATION_GIF, "animated gif"],
  [HydrusFileType.IMAGE_BMP, "bitmap"],
  [HydrusFileType.IMAGE_WEBP, "webp"],
  [HydrusFileType.ANIMATION_WEBP, "animated webp"],
  [HydrusFileType.IMAGE_TIFF, "tiff"],
  [HydrusFileType.IMAGE_QOI, "qoi"],
  [HydrusFileType.IMAGE_ICON, "icon"],
  [HydrusFileType.IMAGE_SVG, "svg"],
  [HydrusFileType.IMAGE_HEIF, "heif"],
  [HydrusFileType.IMAGE_HEIF_SEQUENCE, "heif sequence"],
  [HydrusFileType.IMAGE_HEIC, "heic"],
  [HydrusFileType.IMAGE_HEIC_SEQUENCE, "heic sequence"],
  [HydrusFileType.IMAGE_AVIF, "avif"],
  [HydrusFileType.IMAGE_AVIF_SEQUENCE, "avif sequence"],
  [HydrusFileType.IMAGE_JXL, "jxl"],
  [HydrusFileType.ANIMATION_UGOIRA, "ugoira"],
  [HydrusFileType.APPLICATION_CBZ, "cbz"],
  [HydrusFileType.APPLICATION_FLASH, "flash"],
  [HydrusFileType.APPLICATION_OCTET_STREAM, "application/octet-stream"],
  [HydrusFileType.APPLICATION_YAML, "yaml"],
  [HydrusFileType.APPLICATION_JSON, "json"],
  [HydrusFileType.APPLICATION_CBOR, "cbor"],
  [HydrusFileType.APPLICATION_PDF, "pdf"],
  [HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_DOCX, "docx"],
  [HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_XLSX, "xlsx"],
  [HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_PPTX, "pptx"],
  [HydrusFileType.APPLICATION_DOC, "doc"],
  [HydrusFileType.APPLICATION_XLS, "xls"],
  [HydrusFileType.APPLICATION_PPT, "ppt"],
  [HydrusFileType.APPLICATION_EPUB, "epub"],
  [HydrusFileType.APPLICATION_DJVU, "djvu"],
  [HydrusFileType.APPLICATION_RTF, "rtf"],
  [HydrusFileType.APPLICATION_PSD, "psd"],
  [HydrusFileType.APPLICATION_CLIP, "clip"],
  [HydrusFileType.APPLICATION_SAI2, "sai2"],
  [HydrusFileType.APPLICATION_KRITA, "krita"],
  [HydrusFileType.APPLICATION_XCF, "xcf"],
  [HydrusFileType.APPLICATION_PROCREATE, "procreate"],
  [HydrusFileType.APPLICATION_ZIP, "zip"],
  [HydrusFileType.APPLICATION_RAR, "rar"],
  [HydrusFileType.APPLICATION_7Z, "7z"],
  [HydrusFileType.APPLICATION_GZIP, "gzip"],
  [HydrusFileType.APPLICATION_WINDOWS_EXE, "windows exe"],
  [
    HydrusFileType.APPLICATION_HYDRUS_ENCRYPTED_ZIP,
    "application/hydrus-encrypted-zip",
  ],
  [
    HydrusFileType.APPLICATION_HYDRUS_UPDATE_CONTENT,
    "application/hydrus-update-content",
  ],
  [
    HydrusFileType.APPLICATION_HYDRUS_UPDATE_DEFINITIONS,
    "application/hydrus-update-definitions",
  ],
  [HydrusFileType.AUDIO_M4A, "m4a"],
  [HydrusFileType.AUDIO_MP3, "mp3"],
  [HydrusFileType.AUDIO_OGG, "ogg"],
  [HydrusFileType.AUDIO_FLAC, "flac"],
  [HydrusFileType.AUDIO_MKV, "matroska audio"],
  [HydrusFileType.AUDIO_MP4, "mp4 audio"],
  [HydrusFileType.AUDIO_WAVE, "wave"],
  [HydrusFileType.AUDIO_REALMEDIA, "realaudio"],
  [HydrusFileType.AUDIO_TRUEAUDIO, "tta"],
  [HydrusFileType.AUDIO_WMA, "wma"],
  [HydrusFileType.AUDIO_WAVPACK, "wavpack"],
  [HydrusFileType.TEXT_HTML, "html"],
  [HydrusFileType.TEXT_PLAIN, "plaintext"],
  [HydrusFileType.VIDEO_AVI, "avi"],
  [HydrusFileType.VIDEO_FLV, "flv"],
  [HydrusFileType.VIDEO_MOV, "quicktime"],
  [HydrusFileType.VIDEO_MP4, "mp4"],
  [HydrusFileType.VIDEO_MPEG, "mpeg"],
  [HydrusFileType.VIDEO_WMV, "wmv"],
  [HydrusFileType.VIDEO_MKV, "matroska"],
  [HydrusFileType.VIDEO_OGV, "ogv"],
  [HydrusFileType.VIDEO_REALMEDIA, "realvideo"],
  [HydrusFileType.VIDEO_WEBM, "webm"],
  [HydrusFileType.UNDETERMINED_WM, "wma or wmv"],
  [HydrusFileType.UNDETERMINED_MP4, "mp4 with or without audio"],
  [HydrusFileType.UNDETERMINED_PNG, "png or apng"],
  [HydrusFileType.UNDETERMINED_OLE, "ole file"],
  [HydrusFileType.UNDETERMINED_GIF, "animated or static gif"],
  [HydrusFileType.UNDETERMINED_WEBP, "animated or static webp"],
  [HydrusFileType.APPLICATION_UNKNOWN, "unknown filetype"],
  [HydrusFileType.GENERAL_APPLICATION, "application"],
  [HydrusFileType.GENERAL_APPLICATION_ARCHIVE, "archive"],
  [HydrusFileType.GENERAL_IMAGE_PROJECT, "image project file"],
  [HydrusFileType.GENERAL_AUDIO, "audio"],
  [HydrusFileType.GENERAL_IMAGE, "image"],
  [HydrusFileType.GENERAL_VIDEO, "video"],
  [HydrusFileType.GENERAL_ANIMATION, "animation"],
]);

export const mimetypeToFiletypeEnum: Record<string, HydrusFileType> = {
  collection: HydrusFileType.APPLICATION_HYDRUS_CLIENT_COLLECTION,
  "image/jpe": HydrusFileType.IMAGE_JPEG,
  "image/jpeg": HydrusFileType.IMAGE_JPEG,
  "image/jpg": HydrusFileType.IMAGE_JPEG,
  "image/x-png": HydrusFileType.IMAGE_PNG,
  "image/png": HydrusFileType.IMAGE_PNG,
  "image/apng": HydrusFileType.ANIMATION_APNG,
  "image/gif": HydrusFileType.ANIMATION_GIF,
  "image/bmp": HydrusFileType.IMAGE_BMP,
  "image/webp": HydrusFileType.IMAGE_WEBP,
  "image/tiff": HydrusFileType.IMAGE_TIFF,
  "image/qoi": HydrusFileType.IMAGE_QOI,
  "image/x-icon": HydrusFileType.IMAGE_ICON,
  "image/svg+xml": HydrusFileType.IMAGE_SVG,
  "image/heif": HydrusFileType.IMAGE_HEIF,
  "image/heif-sequence": HydrusFileType.IMAGE_HEIF_SEQUENCE,
  "image/heic": HydrusFileType.IMAGE_HEIC,
  "image/heic-sequence": HydrusFileType.IMAGE_HEIC_SEQUENCE,
  "image/avif": HydrusFileType.IMAGE_AVIF,
  "image/avif-sequence": HydrusFileType.IMAGE_AVIF_SEQUENCE,
  "image/jxl": HydrusFileType.IMAGE_JXL,
  "image/vnd.microsoft.icon": HydrusFileType.IMAGE_ICON,
  image: HydrusFileType.GENERAL_IMAGE,
  "application/x-shockwave-flash": HydrusFileType.APPLICATION_FLASH,
  "application/x-photoshop": HydrusFileType.APPLICATION_PSD,
  "image/vnd.adobe.photoshop": HydrusFileType.APPLICATION_PSD,
  "application/vnd.adobe.photoshop": HydrusFileType.APPLICATION_PSD,
  "application/clip": HydrusFileType.APPLICATION_CLIP,
  "application/sai2": HydrusFileType.APPLICATION_SAI2,
  "application/x-krita": HydrusFileType.APPLICATION_KRITA,
  "application/x-procreate": HydrusFileType.APPLICATION_PROCREATE,
  "image/x-xcf": HydrusFileType.APPLICATION_XCF,
  "application/octet-stream": HydrusFileType.APPLICATION_OCTET_STREAM,
  "application/x-yaml": HydrusFileType.APPLICATION_YAML,
  "PDF document": HydrusFileType.APPLICATION_PDF,
  "application/pdf": HydrusFileType.APPLICATION_PDF,
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_DOCX,
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
    HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_XLSX,
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    HydrusFileType.APPLICATION_MICROSOFT_OPEN_XML_PPTX,
  "application/msword": HydrusFileType.APPLICATION_DOC,
  "application/vnd.ms-word": HydrusFileType.APPLICATION_DOC,
  "application/vnd.ms-excel": HydrusFileType.APPLICATION_XLS,
  "application/msexcel": HydrusFileType.APPLICATION_XLS,
  "application/vnd.ms-powerpoint": HydrusFileType.APPLICATION_PPT,
  "application/powerpoint": HydrusFileType.APPLICATION_PPT,
  "application/mspowerpoint": HydrusFileType.APPLICATION_PPT,
  "application/epub+zip": HydrusFileType.APPLICATION_EPUB,
  "image/vnd.djvu": HydrusFileType.APPLICATION_DJVU,
  "image/vnd.djvu+multipage": HydrusFileType.APPLICATION_DJVU,
  "image/x-djvu": HydrusFileType.APPLICATION_DJVU,
  "text/rtf": HydrusFileType.APPLICATION_RTF,
  "application/rtf": HydrusFileType.APPLICATION_RTF,
  "application/vnd.comicbook+zip": HydrusFileType.APPLICATION_CBZ,
  "application/zip": HydrusFileType.APPLICATION_ZIP,
  "application/vnd.rar": HydrusFileType.APPLICATION_RAR,
  "application/x-7z-compressed": HydrusFileType.APPLICATION_7Z,
  "application/gzip": HydrusFileType.APPLICATION_GZIP,
  "application/json": HydrusFileType.APPLICATION_JSON,
  "application/cbor": HydrusFileType.APPLICATION_CBOR,
  "application/hydrus-encrypted-zip":
    HydrusFileType.APPLICATION_HYDRUS_ENCRYPTED_ZIP,
  "application/hydrus-update-content":
    HydrusFileType.APPLICATION_HYDRUS_UPDATE_CONTENT,
  "application/hydrus-update-definitions":
    HydrusFileType.APPLICATION_HYDRUS_UPDATE_DEFINITIONS,
  application: HydrusFileType.GENERAL_APPLICATION,
  "audio/mp4": HydrusFileType.AUDIO_M4A,
  "audio/mp3": HydrusFileType.AUDIO_MP3,
  "audio/ogg": HydrusFileType.AUDIO_OGG,
  "audio/vnd.rn-realaudio": HydrusFileType.AUDIO_REALMEDIA,
  "audio/x-tta": HydrusFileType.AUDIO_TRUEAUDIO,
  "audio/flac": HydrusFileType.AUDIO_FLAC,
  "audio/x-wav": HydrusFileType.AUDIO_WAVE,
  "audio/wav": HydrusFileType.AUDIO_WAVE,
  "audio/wave": HydrusFileType.AUDIO_WAVE,
  "audio/x-ms-wma": HydrusFileType.AUDIO_WMA,
  "audio/wavpack": HydrusFileType.AUDIO_WAVPACK,
  "text/html": HydrusFileType.TEXT_HTML,
  "text/plain": HydrusFileType.TEXT_PLAIN,
  "video/x-msvideo": HydrusFileType.VIDEO_AVI,
  "video/x-flv": HydrusFileType.VIDEO_FLV,
  "video/quicktime": HydrusFileType.VIDEO_MOV,
  "video/mp4": HydrusFileType.VIDEO_MP4,
  "video/mpeg": HydrusFileType.VIDEO_MPEG,
  "video/x-ms-wmv": HydrusFileType.VIDEO_WMV,
  "video/x-matroska": HydrusFileType.VIDEO_MKV,
  "video/ogg": HydrusFileType.VIDEO_OGV,
  "video/vnd.rn-realvideo": HydrusFileType.VIDEO_REALMEDIA,
  "application/vnd.rn-realmedia": HydrusFileType.VIDEO_REALMEDIA,
  "video/webm": HydrusFileType.VIDEO_WEBM,
  video: HydrusFileType.GENERAL_VIDEO,
  "application/x-ole-storage": HydrusFileType.UNDETERMINED_OLE,
  "unknown filetype": HydrusFileType.APPLICATION_UNKNOWN,
};

export const filetypeCategories: {
  generalFiletype: HydrusFileType;
  filetypes: HydrusFileType[];
}[] = [
  {
    generalFiletype: HydrusFileType.GENERAL_IMAGE,
    filetypes: IMAGES,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_ANIMATION,
    filetypes: ANIMATIONS,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_VIDEO,
    filetypes: VIDEO,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_AUDIO,
    filetypes: AUDIO,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_APPLICATION,
    filetypes: APPLICATIONS,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_IMAGE_PROJECT,
    filetypes: IMAGE_PROJECT_FILES,
  },
  {
    generalFiletype: HydrusFileType.GENERAL_APPLICATION_ARCHIVE,
    filetypes: ARCHIVES,
  },
];

export function filetypeFromMime(mime: string) {
  return mimetypeToFiletypeEnum[mime] ?? HydrusFileType.APPLICATION_UNKNOWN;
}

export function categoryFromFiletype(
  filetype: HydrusFileType | undefined,
): HydrusFileType | undefined {
  if (!filetype) {
    return undefined;
  }
  for (const { generalFiletype, filetypes } of filetypeCategories) {
    if (filetype === generalFiletype || filetypes.includes(filetype)) {
      return generalFiletype;
    }
  }
  return undefined;
}
