export enum SortFilesBy {
  FILESIZE = 0,
  DURATION = 1,
  IMPORT_TIME = 2,
  MIME = 3,
  RANDOM = 4,
  WIDTH = 5,
  HEIGHT = 6,
  RATIO = 7,
  NUM_PIXELS = 8,
  NUM_TAGS = 9,
  MEDIA_VIEWS = 10,
  MEDIA_VIEWTIME = 11,
  APPROX_BITRATE = 12,
  HAS_AUDIO = 13,
  FILE_MODIFIED_TIMESTAMP = 14,
  FRAMERATE = 15,
  NUM_FRAMES = 16,
  NUM_COLLECTION_FILES = 17,
  LAST_VIEWED_TIME = 18,
  ARCHIVED_TIMESTAMP = 19,
  HASH = 20,
  PIXEL_HASH = 21,
  BLURHASH = 22,
  AVERAGE_COLOUR_LIGHTNESS = 23,
  AVERAGE_COLOUR_CHROMATIC_MAGNITUDE = 24,
  AVERAGE_COLOUR_CHROMATICITY_GREEN_RED = 25,
  AVERAGE_COLOUR_CHROMATICITY_BLUE_YELLOW = 26,
  AVERAGE_COLOUR_HUE = 27,
}

export const sortFilesByEnumToString: Map<SortFilesBy, string> = new Map([
  [SortFilesBy.FILESIZE, "File size"],
  [SortFilesBy.DURATION, "Duration"],
  [SortFilesBy.IMPORT_TIME, "Import time"],
  [SortFilesBy.MIME, "MIME type"],
  [SortFilesBy.RANDOM, "Random"],
  [SortFilesBy.WIDTH, "Width"],
  [SortFilesBy.HEIGHT, "Height"],
  [SortFilesBy.RATIO, "Ratio"],
  [SortFilesBy.NUM_PIXELS, "Number of pixels"],
  [SortFilesBy.NUM_TAGS, "Number of tags"],
  [SortFilesBy.MEDIA_VIEWS, "Media views"],
  [SortFilesBy.MEDIA_VIEWTIME, "Media view time"],
  [SortFilesBy.APPROX_BITRATE, "Approximate bitrate"],
  [SortFilesBy.HAS_AUDIO, "Has audio"],
  [SortFilesBy.FILE_MODIFIED_TIMESTAMP, "File modified timestamp"],
  [SortFilesBy.FRAMERATE, "Framerate"],
  [SortFilesBy.NUM_FRAMES, "Number of frames"],
  [SortFilesBy.NUM_COLLECTION_FILES, "Number of collection files"],
  [SortFilesBy.LAST_VIEWED_TIME, "Last viewed time"],
  [SortFilesBy.ARCHIVED_TIMESTAMP, "Archived timestamp"],
  [SortFilesBy.HASH, "Hash"],
  [SortFilesBy.PIXEL_HASH, "Pixel hash"],
  [SortFilesBy.BLURHASH, "Blurhash"],
  [SortFilesBy.AVERAGE_COLOUR_LIGHTNESS, "Average color lightness"],
  [
    SortFilesBy.AVERAGE_COLOUR_CHROMATIC_MAGNITUDE,
    "Average color chromatic magnitude",
  ],
  [
    SortFilesBy.AVERAGE_COLOUR_CHROMATICITY_GREEN_RED,
    "Average color chromaticity green-red",
  ],
  [
    SortFilesBy.AVERAGE_COLOUR_CHROMATICITY_BLUE_YELLOW,
    "Average color chromaticity blue-yellow",
  ],
  [SortFilesBy.AVERAGE_COLOUR_HUE, "Average color hue"],
]);
